### ISSUE TITLE
Header Component

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/sbc-site#1]
## Objective
Implement header component

## Tasks
- [ ] Adjust styles
- [ ] Implement Search
- [ ] Add header to all site pages
- [ ] (Insert tasks here)

## Acceptance Criteria
- [ ] Header present on all site pages
- [ ] Nav functionality implemented
- [ ] Search functionality works as expected
- [ ] Styling matches mockups
