### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/sbc-site#11]
## Objective
Implement home page

## Tasks
- [ ] Apply styles
- [ ] Implement carousel (beacons)
- [ ] Add Newsletter Signup section 
- [ ] Social @southbronxcommunity section 
- [ ] (Insert tasks here)

## Acceptance Criteria
- [ ] Home page content and style matches mockups
