### ISSUE TITLE
[Home Page] Apply Styles

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/sbc-site#12]
## Objective
Apply styles specified in mockups to Home Page

## Tasks
- [ ] Announcement banner
- [ ] Hero + Mission of Support
- [ ] Newsletter signup
- [ ] Quote and image

## Acceptance Criteria
- [ ] Home page content and style matches mockups
- [ ] Newsletter signup incorporated into the page
