### ISSUE TITLE
[Home Page] Carousel block

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/sbc-site#13]
## Objective
Implement carousel component for beacon section of the home page

## Tasks
- [x] Create beacons block
- [x] Add innerblock template to create block scaffold
- [x] Create carousel block
- [x] Add media upload component
- [x] Add rich text component for quote
- [ ] Add control bar to editor for text align and image replacement
- [ ] Template for image upload
- [ ] Add contents to save function and style
- [ ] Add arrow to scroll through beacons

## Acceptance Criteria
- [ ] Carousel component style matches specification in mockups
- [ ] Carousel exhibits expected functionality
