### ISSUE TITLE
[Home Page] Social @southbronxcommunity

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/sbc-site#14]
## Objective
Implement social component

## Tasks
- [ ] Clarify requirements on behavior w/Noele

## Acceptance Criteria
- [ ] Social component is present on the home page
- [ ] Social component is styled and functioning as specified in mockups
