### ISSUE TITLE
WWA - Mission Page

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/sbc-site#15]
## Objective
Implement Who We Are - Mission page

## Tasks
- [ ] Template/Scaffolding
     - [ ] Hero
     - [ ] Mission and History
     - [ ] Image + Quote
- [ ] Apply styles
- [ ] Implement floating side menu
- [ ] (Insert tasks here)

## Acceptance Criteria
- [ ] Page matches functionality and style specified in mockups
