### ISSUE TITLE
[WWA-Mission] Template and Scaffold

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/sbc-site#16]
## Objective
Template and scaffolding for Who We Are - Mission page

## Tasks
- [x] Make groups to mirror design
- [x] Add copy and images

## Acceptance Criteria
- [ ] Page copy and format matches mockups
