### ISSUE TITLE
[WWA-Mission] Apply Styles

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/sbc-site#17]
## Objective
Apply styles to Who We Are - Mission page to match mockups

## Tasks
- [x] Add correct text and sizes
- [ ] Place circular image to be cut off at the right place

## Acceptance Criteria
- [ ] Page style matches mockups
