### ISSUE TITLE
WWA - Model Page

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/sbc-site#18]
## Objective
Implement Who We Are - Model page to match mockups

## Tasks
- [ ] Template / Scaffold
- [ ] Apply Styles
- [ ] Implement floating side menu
- [ ] (Insert tasks here)

## Acceptance Criteria
- [ ] Page style and content matches mockups
