### ISSUE TITLE
[Header] Apply styles

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/sbc-site#2]
## Objective
Apply styling to header specified in mockups

## Tasks
- [ ] Spacing for logo and links

## Acceptance Criteria
- [ ] Style of header matches style in mockups

**Comment by alegzandach** [comment]
### Tasks

- [ ] Spacing for logo and links
