### ISSUE TITLE
[WWA-Model] Implement Floating side menu

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/sbc-site#20]
## Objective
Implement floating side menu and add to the Who We Are - Model page

## Tasks
- [x] Add column to page
- [ ] Stick to top of page on scroll

## Acceptance Criteria
- [ ] Side menu appears and floats as user scrolls down the page
- [ ] Side menu navigation works as expected
