### ISSUE TITLE
WWA - People Page

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/sbc-site#21]
## Objective
Implement Who We Are - Our People page

## Tasks
- [ ] Template / Scaffold
- [ ] Apply styles
- [ ] Implement floating side menu
- [ ] Implementn pagination for each menu entry
- [ ] Backend support for personnel
- [ ] (Insert tasks here)

## Acceptance Criteria
- [ ] Who We Are - Our People has style, content and functionality which matches mockups
