### ISSUE TITLE
[WWA-People] - Apply Styles

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/sbc-site#23]
## Objective
Apply styles to Who We Are - Our People page

## Tasks
- [ ] Fonts and sizing
- [ ] Adjust padding for headers and paragraph
- [ ] Adjust margin for sidebar

## Acceptance Criteria
- [ ] Who We Are - Our People page is styled as specified in mockups
