### ISSUE TITLE
[WWA-People] - Implement floating side menu

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/sbc-site#24]
## Objective
Implement floating side menu and add to the Who We Are - People page

## Tasks
- [x] Add column for side menu
- [ ] Stick to top when scrolling

## Acceptance Criteria
- [ ] Side menu appears and floats as user scrolls down the page
- [ ] Side menu navigation works as expected
