### ISSUE TITLE
[WWA-People] - Implement pagination

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/sbc-site#25]
## Objective
Implement pagination and add to the Who We Are - People page

## Tasks
- [ ] Add page breaks at regular intervals? Or place strategically to encapsulate groups if possible

## Acceptance Criteria
- [ ] Page count and nav function as expected
- [ ] Functionality in place to view last, next, first and last pages
