### ISSUE TITLE
[WWA-People] - Personnel block

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/sbc-site#26]
## Objective
Create custom block that allows user to add personnel

## Tasks
- [x] Add image component
- [x] Add name and title field
- [x] Add bio field
- [x] Make container responsive to wordpress controls
- [x] Add correct font and fontsize
- [ ] Add correct padding 

## Acceptance Criteria
- [ ] Functionality in place to retrieve personnel info to be displayed on the site from the backend
