### ISSUE TITLE
News & Events Page

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/sbc-site#27]
## Objective
Implement News & Events page

## Tasks
- [ ] Template/Scaffold
- [ ] Implement calendar
- [ ] Backend support for news & events
- [ ] Populate top events below
- [ ] Implement floating side nav
- [ ] Implement pagination for each menu entry
- [ ] Shoutout section 
- [ ] (Insert tasks here)

## Acceptance Criteria
- [ ] News & Events page has content, format, style and functionality as specified in mockups
