### ISSUE TITLE
[N&E] Template / Scaffold

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/sbc-site#28]
## Objective
Scaffold out the News & Events page

## Tasks
- [ ] Add calendar component
- [ ] Add events component
- [ ] Add sidebar

## Acceptance Criteria
- [ ] News & Events page has content and format specified in mockups
