### ISSUE TITLE
[N&E] Implement calendar

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/sbc-site#29]
## Objective
Implement calendar to be displayed on the News & Events page

## Tasks
- [ ] Get requirements from client
- [ ] Create block to embed a google calendar iframe and query gcal for events.
OR
- [ ] Develop new strategy, probably involving an existing calendar plugin that lets the client create new events from the wordpress dashboard. 

## Acceptance Criteria
- [ ] News & Events page has content and format specified in mockups
