### ISSUE TITLE
[N&E] Populate top events below

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/sbc-site#31]
## Objective
Utilize backend to populate top events to be displayed below the calendar. 

## Tasks
IF client needs to use gcal
- [ ] Create block to retrieve gcal events and display them

IF client needs new strategy
- [ ] Create block to dynamically create listings using a plugins events table

- [ ] block will need pagination  (most likely via innerblocks) and will need dynamic anchor tagging

## Acceptance Criteria
- [ ] Top events visible on the News & Events page below the calendar
