### ISSUE TITLE
[N&E] Implement floating side nav

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/sbc-site#32]
## Objective
Implement floating side nav to be displayed on the News & Events page. 

## Tasks
- [ ] Leverage work from existing pages

## Acceptance Criteria
- [ ] Nav appears on the left side of the page
- [ ] Nav moves down the page as user scrolls
- [ ] Nav functions/routes to expected sections
