### ISSUE TITLE
[N&E] Implement pagination

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/sbc-site#33]
## Objective
Implement pagination for each menu item on the News & Events page. 

## Tasks
- [ ] (Insert tasks here)

## Acceptance Criteria
- [ ] Page count and nav function as expected
- [ ] User is able to move to first, last, next, or previous pages
