### ISSUE TITLE
[N&E] Apply styles

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/sbc-site#35]
## Objective
Apply styles to all components on the News & Events page

## Tasks
- [ ] Padding for calendar
- [ ] Padding for events
- [ ] Spacing for events
- [ ] Font and fontsize for events

## Acceptance Criteria
- [ ] Styling on the News & Events page matches specification in mockups
