### ISSUE TITLE
Enroll Page

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/sbc-site#36]
## Objective
Implement Enroll page

## Tasks
- [ ] Template / Scaffold
- [ ] Implement Contact Admissions Team
- [ ] Implement floating side menu
- [ ] Apply styles
- [ ] (Insert tasks here)

## Acceptance Criteria
- [ ] Enroll page has content, format, functionality and style specified in mockups
