### ISSUE TITLE
[Enroll] Implement Contact Admissions Team

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/sbc-site#38]
## Objective
Implement Contact Admissions Team button

## Tasks
- [ ] Add button to sidemenu
- [ ] Add link to button

## Acceptance Criteria
- [ ] When a user clicks button, user is able to contact the admissions team
