### ISSUE TITLE
[Enroll] Implement floating side menu

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/sbc-site#39]
## Objective
Implement floating side nav to be displayed on the Enroll page. 

## Tasks
- [ ] Leverage work from other pages

## Acceptance Criteria
- [ ] Nav appears on the left side of the page
- [ ] Nav moves down the page as user scrolls
- [ ] Nav functions/routes to expected sections
