### ISSUE TITLE
Add header to all pages

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/sbc-site#4]
## Objective
Add header to all pages

## Tasks
- [x] Add logo
- [x] Add links
- [ ] Add sitewide banner
- [x] Add to all pages

## Acceptance Criteria
- [ ] Header is present on all site pages

**Comment by alegzandach** [comment]
### Tasks

- [x] Add header to all site pages
