### ISSUE TITLE
[Enroll] Apply styles

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/sbc-site#40]
## Objective
Apply styles specified in mockups to the Enroll page. 

## Tasks
- [ ] Bottom callout section
- [ ] Style button with color, font, fontsize, spacing, alignment and padding
- [ ] Leverage rest of style from other pages

## Acceptance Criteria
- [ ] Enroll page has style specified in mockups
