### ISSUE TITLE
Careers Page

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/sbc-site#41]
## Objective
Implement Careers page. 

## Tasks
- [ ] Template / Scaffold
- [ ] Apply styles
- [ ] Implement Complete an Application
- [ ] Quote / Callout section
- [ ] (Insert tasks here)

## Acceptance Criteria
- [ ] Careers page has content, format, style and functionality specified in mockups
