### ISSUE TITLE
[Contact] Implement form submission

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/sbc-site#48]
## Objective
Implement submission of form on the Contact Us page. 

## Tasks
- [ ] Add mail service to site
- [ ] Add send to address
- [ ] Format message

## Acceptance Criteria
- [ ] Form submits user information entered to SBC
