### ISSUE TITLE
Footer Component

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/sbc-site#5]
## Objective
Implement footer component

## Tasks
- [ ] (Insert tasks here)

## Acceptance Criteria
- [ ] Footer is present on all site pages
- [ ] Footer is styled as specified in mockups
- [ ] User is able to sign up for the newsletter
- [ ] Footer quicklinks work as expected
- [ ] Footer contains styled contact info section
