### ISSUE TITLE
[Footer] Apply styles

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/sbc-site#6]
## Objective
Apply styles specified in mockups to footer

## Tasks
- [ ] Add font and font sizing
- [ ] Add correct padding for elements
- [ ] Space social buttons

## Acceptance Criteria
- [ ] Footer is styled in accordance with mockups
