### ISSUE TITLE
[Footer] Newsletter Signup

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/sbc-site#7]
## Objective
Implement newsletter signup functionality in the footer

## Tasks
- [ ] Add newsletter form from wpforms
- [ ] style button

## Acceptance Criteria
- [ ] User is able to sign up for the SBC newsletter
- [ ] Newsletter signup is added to the footer
