### ISSUE TITLE
[Footer] Implement Quicklinks

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/sbc-site#8]
## Objective
Implement quicklinks in the footer

## Tasks
- [ ] create and add menu

## Acceptance Criteria
- [ ] Quicklinks are present in the footer
- [ ] Quicklinks navigate to expected pages
