### ISSUE TITLE
[Footer] Contact Info

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/sbc-site#9]
## Objective
Add contact info section to the footer

## Tasks
- [ ] Add section with copy

## Acceptance Criteria
- [ ] Contact Info section is present in footer
- [ ] Contact Info content matches mockups
